GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcyMDhmMTEwMGFmY2ZhNTA5ZGM2MDAiLCJpYXQiOjE2NTE2OTc2NTcsImV4cCI6MTY1MTY5NzY3N30.wNWebe-nbk7VM6AKQPVPwfHvv-Xyy3yUsfCGpLVE9go
###

POST http://localhost:3000/register
Content-Type: application/json

{
    "first_name": "Quang",
    "middle_name": "Minh",
    "last_name": "Bui",
    "birthdate": "2001-05-26",
    "email": "quang.bui@email.com",
    "password": "789123456",
    "phone": "0793936457",
    "location": {
        "num": "355/15",
        "street": "Sư Vạn Hạnh",
        "ward": "12",
        "district": "10",
        "city": "Ho Chi Minh City"
    }
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "ha.ung@email.com",
    "password": "123456789"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "user_id": "627208f1100afcfa509dc600",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcyMDhmMTEwMGFmY2ZhNTA5ZGM2MDAiLCJpYXQiOjE2NTE2OTc2NDd9.rahdhsMQ9tqgWEv8cDxXUpsWb6R0HDlzdmMopOfel30"
}

### 
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcyMDhmMTEwMGFmY2ZhNTA5ZGM2MDAiLCJpYXQiOjE2NTE2OTc2NDd9.rahdhsMQ9tqgWEv8cDxXUpsWb6R0HDlzdmMopOfel30"
}