GET http://localhost:3000/user
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjcyMDhmMTEwMGFmY2ZhNTA5ZGM2MDAiLCJpYXQiOjE2NTE2NTA3OTN9.7oEl6caERG2EcnLCfMw5kQg66K8rJv2avoGOlzj_w50

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "first_name": "Quang",
    "middle_name": "Minh",
    "last_name": "Bui",
    "birthdate": "2001-05-26",
    "email": "quang.bui@email.com",
    "password": "789123456",
    "phone": "0793936457",
    "location": {
        "num": "355/15",
        "street": "Sư Vạn Hạnh",
        "ward": "12",
        "district": "10",
        "city": "Ho Chi Minh City"
    }
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "ha.ung@email.com",
    "password": "123456789"
}