export const districtsHCMC = [
    {label:'All',value:''},
    {label:'District 1',value:'1'},
    {label:'District 2',value:'2'},
    {label:'District 3',value:'3'},
    {label:'District 4',value:'4'},
    {label:'District 5',value:'5'},
    {label:'District 6',value:'6'},
    {label:'District 7',value:'7'},
    {label:'District 8',value:'8'},
    {label:'District 9',value:'9'},
    {label:'District 10',value:'10'},
    {label:'District 11',value:'11'},
    {label:'District 12',value:'12'},
    {label:'Binh Thanh',value:'Binh Thanh'},
    {label:'Thu Duc',value:'Thu Duc'},
    {label:'Go Vap',value:'Go Vap'},
    {label:'Phu Nhuan',value:'Phu Nhuan'},
    {label:'Tan Binh',value:'Tan Binh'},
    {label:'Tan Phu',value:'Tan Phu'},
    {label:'Binh Tan',value:'Binh Tan'},
    {label:'Nha Be',value:'Nha Be'},
    {label:'Hoc Mon',value:'Hoc Mon'},
    {label:'Binh Chanh',value:'Binh Chanh'},
    {label:'Cu Chi',value:'Cu Chi'},
    {label:'Can Gio',value:'Can Gio'}
  ]

export const districtsHanoi = [
  {label:'All',value:''},
  {label:'Ba Dinh',value:'Ba Dinh'},
  {label:'Dong Da',value:'Dong Da'},
  {label:'Ha Ba Trung',value:'Hai Ba Trung'},
  {label:'Hoan Kiem',value:'Hoan Kiem'},
  {label:'Bac Tu Liem',value:'Bac Tu Liem'},
  {label:'Nam Tu Liem',value:'Nam Tu Liem'},
  {label:'Cau Giay',value:'Cau Giay'},
  {label:'Ha Dong',value:'Ha Dong'},
  {label:'Hoang Mai',value:'Hoang Mai'},
  {label:'Long Bien',value:'Long Bien'},
  {label:'Thanh Xuan',value:'Thanh Xuan'},
  {label:'Tay Ho',value:'Tay Ho'},
]